### ISSUE TITLE
Ruby 2.5

### ISSUE THREAD

**Issue by Daniel-ltw** [seattlerb/sexp_processor#24]
```
/usr/local/bundle/gems/sexp_processor-4.10.0/lib/sexp.rb:223:in `inject': stack level too deep (SystemStackError)

	from /usr/local/bundle/gems/sexp_processor-4.10.0/lib/sexp.rb:223:in `mass'

	from /usr/local/bundle/gems/sexp_processor-4.10.0/lib/sexp.rb:223:in `block in mass'

	from /usr/local/bundle/gems/sexp_processor-4.10.0/lib/sexp.rb:223:in `each'

	from /usr/local/bundle/gems/sexp_processor-4.10.0/lib/sexp.rb:223:in `inject'

	from /usr/local/bundle/gems/sexp_processor-4.10.0/lib/sexp.rb:223:in `mass'

	from /usr/local/bundle/gems/sexp_processor-4.10.0/lib/sexp.rb:223:in `block in mass'

	from /usr/local/bundle/gems/sexp_processor-4.10.0/lib/sexp.rb:223:in `each'

	from /usr/local/bundle/gems/sexp_processor-4.10.0/lib/sexp.rb:223:in `inject'

	 ... 160 levels...
```

Could someone investigate this?

**Comment by presidentbeef** [comment]
Can you provide some context? For example...that doesn't look like a Ruby 2.5 stacktrace.

**Comment by Daniel-ltw** [comment]
Been running rubycritic. It was spitting this error. 

Ran this on my local box and this is the stacktrace that I got. 

```
Traceback (most recent call last):
	165: from /usr/local/bundle/bin/rubycritic:23:in `<main>'
	164: from /usr/local/bundle/bin/rubycritic:23:in `load'
	163: from /usr/local/bundle/gems/rubycritic-3.3.0/bin/rubycritic:10:in `<top (required)>'
	162: from /usr/local/bundle/gems/rubycritic-3.3.0/lib/rubycritic/cli/application.rb:20:in `execute'
	161: from /usr/local/bundle/gems/rubycritic-3.3.0/lib/rubycritic/commands/default.rb:19:in `execute'
	160: from /usr/local/bundle/gems/rubycritic-3.3.0/lib/rubycritic/commands/default.rb:24:in `critique'
	159: from /usr/local/bundle/gems/rubycritic-3.3.0/lib/rubycritic/analysers_runner.rb:27:in `run'
	158: from /usr/local/bundle/gems/rubycritic-3.3.0/lib/rubycritic/analysers_runner.rb:27:in `each'
	 ... 153 levels...
	  4: from /usr/local/bundle/gems/sexp_processor-4.10.0/lib/sexp.rb:223:in `each'
	  3: from /usr/local/bundle/gems/sexp_processor-4.10.0/lib/sexp.rb:223:in `block in mass'
	  2: from /usr/local/bundle/gems/sexp_processor-4.10.0/lib/sexp.rb:223:in `mass'
	  1: from /usr/local/bundle/gems/sexp_processor-4.10.0/lib/sexp.rb:223:in `inject'
/usr/local/bundle/gems/sexp_processor-4.10.0/lib/sexp.rb:223:in `each': stack level too deep (SystemStackError)
```

Could this be a rubycritic analyzer problem?

**Comment by presidentbeef** [comment]
Kind of hard to tell where the loop is occurring without the missing steps.

Is this only happening on Ruby 2.5? I would file an issue with rubycritic, too.

**Comment by Daniel-ltw** [comment]
Yeah just ruby 2.5 at the moment. 

Notice a similar issue with brakeman as well. Uses it's own parser. 
Parsing ruby 2.5 syntax needs to be change or something?

**Comment by Daniel-ltw** [comment]
Just so you know, this is the error that brakeman is spitting out. 

```
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp.rb:106:in `hash': stack level too deep (SystemStackError)
	from /usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp.rb:106:in `hash'
	from /usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp.rb:106:in `hash'
	from /usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp.rb:106:in `hash'
	from /usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp.rb:106:in `hash'
	from /usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp.rb:106:in `hash'
	from /usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp.rb:106:in `hash'
	from /usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp.rb:106:in `hash'
	from /usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp.rb:106:in `hash'
	 ... 258 levels...
	from /usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/commandline.rb:20:in `start'
	from /usr/local/bundle/gems/brakeman-4.1.1/bin/brakeman:8:in `<top (required)>'
	from /usr/local/bundle/bin/brakeman:23:in `load'
	from /usr/local/bundle/bin/brakeman:23:in `<main>'
```

Both fails with my ruby 2.5 change in our project. With ruby 2.4.3, it both were fine.

**Comment by presidentbeef** [comment]
I haven't seen that happening.

Can you provide a minimal example to reproduce it? In Brakeman you can run with `-d` to get a better idea of what file might be causing the issue.

**Comment by presidentbeef** [comment]
btw rubycritic and Brakeman both use ruby_parser

**Comment by Daniel-ltw** [comment]
```
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp.rb:106:in `hash'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp.rb:106:in `hash'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp.rb:106:in `hash'
/usr/local/bundle/gems/brakeman-4.1.1/bundle/ruby/2.3.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:425:in `key?'
/usr/local/bundle/gems/brakeman-4.1.1/bundle/ruby/2.3.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:425:in `block in []'
/usr/local/bundle/gems/brakeman-4.1.1/bundle/ruby/2.3.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:425:in `each'
/usr/local/bundle/gems/brakeman-4.1.1/bundle/ruby/2.3.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:425:in `find'
/usr/local/bundle/gems/brakeman-4.1.1/bundle/ruby/2.3.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:425:in `[]'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:81:in `replace'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:82:in `replace'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:70:in `process_default'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:77:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:61:in `block in process_default'
(eval):3:in `map!'
(eval):3:in `map!'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:59:in `process_default'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:173:in `process_call'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:61:in `block in process_default'
(eval):3:in `map!'
(eval):3:in `map!'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:59:in `process_default'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:808:in `process_if_branch'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:683:in `block in process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each_with_index'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:810:in `process_if_branch'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:683:in `block in process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each_with_index'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:810:in `process_if_branch'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:683:in `block in process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each_with_index'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:810:in `process_if_branch'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:683:in `block in process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each_with_index'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:810:in `process_if_branch'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:683:in `block in process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each_with_index'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:810:in `process_if_branch'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:683:in `block in process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each_with_index'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:810:in `process_if_branch'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:683:in `block in process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each_with_index'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:810:in `process_if_branch'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:683:in `block in process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each_with_index'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:810:in `process_if_branch'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:683:in `block in process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each_with_index'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:810:in `process_if_branch'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:683:in `block in process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each_with_index'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:810:in `process_if_branch'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:683:in `block in process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each_with_index'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:810:in `process_if_branch'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:683:in `block in process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `each_with_index'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:682:in `process_if'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/lib/processor_helper.rb:13:in `block in process_all!'
(eval):3:in `map!'
(eval):3:in `map!'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/lib/processor_helper.rb:11:in `process_all!'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:375:in `block in process_defs'
/usr/local/bundle/gems/brakeman-4.1.1/bundle/ruby/2.3.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:452:in `scope'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:373:in `process_defs'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/library_processor.rb:32:in `process_defn'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/lib/processor_helper.rb:13:in `block in process_all!'
(eval):3:in `map!'
(eval):3:in `map!'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/lib/processor_helper.rb:11:in `process_all!'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/lib/module_helper.rb:54:in `handle_class'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/library_processor.rb:24:in `process_class'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/base_processor.rb:114:in `block in process_block'
(eval):3:in `map!'
(eval):3:in `map!'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/base_processor.rb:113:in `process_block'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/library_processor.rb:20:in `process_library'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processor.rb:99:in `process_lib'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/scanner.rb:205:in `process_lib'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/scanner.rb:199:in `block in process_libs'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/scanner.rb:302:in `block in track_progress'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/scanner.rb:299:in `each'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/scanner.rb:299:in `track_progress'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/scanner.rb:197:in `process_libs'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/scanner.rb:49:in `process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman.rb:352:in `scan'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman.rb:76:in `run'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/commandline.rb:133:in `run_brakeman'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/commandline.rb:118:in `regular_report'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/commandline.rb:142:in `run_report'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/commandline.rb:35:in `run'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/commandline.rb:20:in `start'
/usr/local/bundle/gems/brakeman-4.1.1/bin/brakeman:8:in `<top (required)>'
/usr/local/bundle/bin/brakeman:23:in `load'
/usr/local/bundle/bin/brakeman:23:in `<main>'
```

This is a output I got from interrupting when the 'stack level too deep' is happening. 


With the -d on brakeman, it does seem that the parsing is done. 
This stack level too deep is happening at the processing libs phase. 

Starting to wonder if there are syntax error on our part.

**Comment by presidentbeef** [comment]
Syntax error doesn't make sense. It would be the same on 2.5 as any other Ruby version.

Can you figure out the file that's causing the problem?

**Comment by Daniel-ltw** [comment]
Yeah, it is a 1332 line file in a private project. 

Not sure how to un-wrap this mess with the error that we are getting right now. 
I guess to debug this problem, I might need to drop print outs in the following lines:
```
/usr/local/bundle/gems/brakeman-4.1.1/bundle/ruby/2.3.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:425:in `key?'
/usr/local/bundle/gems/brakeman-4.1.1/bundle/ruby/2.3.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:425:in `block in []'
/usr/local/bundle/gems/brakeman-4.1.1/bundle/ruby/2.3.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:425:in `each'
/usr/local/bundle/gems/brakeman-4.1.1/bundle/ruby/2.3.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:425:in `find'
/usr/local/bundle/gems/brakeman-4.1.1/bundle/ruby/2.3.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:425:in `[]'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:81:in `replace'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:82:in `replace'
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb:70:in `process_default'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:77:in `block in process'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
```

If you have a better idea, I would be glad to hear it and get to the bottom of this problem. 

Cheers

**Comment by presidentbeef** [comment]
I usually start deleting half of the file at a time to figure out which part is causing the problem.

It's *very* weird that both Brakeman and rubycritic would have the same problem. It suggests maybe a Ruby 2.5 bug or change in behavior. Can you tell if it's the same file?

My guess is the AST is really large for that file and what used to be a safe recursion depth is now too deep in Ruby 2.5.

Maybe try

```
export RUBY_THREAD_VM_STACK_SIZE=2000000
```

Then run Brakeman/rubycritic and see if that makes a difference (other than the size of the stack trace increasing).

**Comment by Daniel-ltw** [comment]
Yeah, I think the recursion depth could be the problem here. 

Here are some debugging message that I got:
```
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb::61:: e = s(:lasgn, :rs, s(:call, s(:const, :Model), :find_by_sql, s(:lvar, :query)))
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb::71:: type = lasgn
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb::72:: context = [:block, :until, :iter, :lasgn, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :defs]
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb::71:: type = call
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb::72:: context = [:lasgn, :block, :until, :iter, :lasgn, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :defs]
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb::61:: e = s(:const, :Model)
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb::71:: type = const
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb::72:: context = [:call, :lasgn, :block, :until, :iter, :lasgn, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :defs]
/usr/local/bundle/gems/brakeman-4.1.1/lib/brakeman/processors/alias_processor.rb::61:: e = s(:lvar, :query)
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb::71:: type = lvar
/usr/local/bundle/gems/brakeman-4.1.1/lib/ruby_parser/bm_sexp_processor.rb::72:: context = [:call, :lasgn, :block, :until, :iter, :lasgn, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :if, :defs]
```

Those are the last few print out before the Traceback occured. 
And we have a huge 'e' 50-100 lines up those print outs. 

Also with the VM_STACK_SIZE change I could only get it up to 260 levels, which is still insufficient. 

I guess we got to know what the real problem is from this.

**Comment by Daniel-ltw** [comment]
Just found this example which could be related to my issue. 

https://github.com/koshigoe/ruby-2.5.0-stack-level-too-deep

This problem is not related to sexp_processor, so I am closing this issue. 

Cheers @presidentbeef for all the assistance so far into debugging my problem.

**Comment by Daniel-ltw** [comment]
To further explain this ruby 2.5 issue, the following link/comment does it pretty well. 

https://qiita.com/koshigoe/items/7acebbab7b44fa2b35bc#comment-8b42d6c25e4e93b66fe2

Some how ruby 2.5 being compiled on alpine 3.7 has a different behaviour compared to ruby 2.4.3 compiled on alpine 3.7. This only happens in deep AST, as you can see from the next comment.
